### ISSUE TITLE
[1.12.2 v0.3.0] No RF transfer?

### ISSUE THREAD

**Issue by VallenFrostweaver** [ArclightTW/Tiny-Reactors#4]
So I decided to see how well this would interact with Thermal Foundation/Expansion/Dynamics as well as RFTools and it doesn't seem to transfer power. It will store RF in the Reactor Energy Port (REP). It will transfer power to a Capacitor block placed next to the REP but anything Thermal/RFTools won't accept power including cables and Energy Cells. When I break the Capacitor block with a pick the RF in it is gone (might be as intended). How is this currently to supply power to something?

**Comment by ArclightTW** [comment]
Thermal Foundation/Expansion/Dynamics uses their own RF system rather than the inbuilt Forge Energy - their method has a slightly different signature to Forge's internal so there is no cross transfer.  However, I am about to put up a new version that should address this and a number of other issues.

**Comment by ArclightTW** [comment]
Please let me know if this is resolved in the new version and I will close accordingly.

**Comment by VallenFrostweaver** [comment]
The Capacitor block is no longer in the mod (as intended?). The Textures on the Reactor Controller are black for the beacon inside until the structure is complete then it is slightly lit and doesn't spin anymore (as intended?). Power is generated once structure is complete (and I see the new GUI when clicking on the Controller - looks clean and I likes it). No power is transferred to RFTools or Thermal suite items (as these are what I'm using my testing on).

**Comment by ArclightTW** [comment]
> The Capacitor block is no longer in the mod (as intended?).

Correct, the Capacitors have been temporarily removed so that I can work on reimplementing them in a less performance derpy manner.

> The Textures on the Reactor Controller are black for the beacon inside until the structure is complete then it is slightly lit and doesn't spin anymore (as intended?).

I am trying to figure out how I want the Reactor Controller to look as I cannot decide on a look. Any thoughts?

> Power is generated once structure is complete (and I see the new GUI when clicking on the Controller - looks clean and I likes it).

Thanks, glad you like the UI - tried to keep it minimal as it doesn't do anything but provide information.

> No power is transferred to RFTools or Thermal suite items (as these are what I'm using my testing on).

This is going to become a bug bear of mine, I can tell v_v I will look into this when I am back home this evening (as I am working again now) and see if I can get the RF suite to play nice.

**Thanks for your continual support to point out flaws in the mod; it makes my life easier as a developer and can allow patches and fixes to be rolled out more quickly.**

**Comment by VallenFrostweaver** [comment]
No power to Immersive Engineering, Actually Additions (which uses Tesla and RF), or IC2 either. What power system or mod(s) were you using to test your setup?
Also, not sure if you saw my edit on the comment above.

As for the reactor look:
I actually liked Reactor Controller spinning beacon dependant on power given look. The little buttons on the bottom right of it get cut off by the hole though and I would either make it just a grid of 4 or 6 or have a line of them 4-6 long. The texture of the reactor blocks while appropriate seems a bit circularly repetitive (place a bunch down and you see the circular shading on them) and a little hi-res in comparison to the iron bars of the energy port. A simple dark grey color with a texture like that of standard minecraft black concrete would give it a better vanilla/simple feel. Perhaps a second circle around the porthole of the Reactor Controller opening as well to make it look like a "seal" is on there might take the edge off the circle being there too.  Just some suggestions. Don't want to tell you how to do your mod.

**Comment by ArclightTW** [comment]
All my content, right now, is Forge Energy based.  I need to get a hold of Tesla, RF and IC2 to get the suite working; it's such a pain in the ass having such a wide range of power systems out there... I can see why Forge started implementing their own! 

As for the reactor not starting until the Controller is clicked, that is intended but I am of the opinion that it is a pain the ass.  I don't want the reactor to sit and check blocks over and over though, so trying to work out a good compromise right now.

Yeah, I think I preferred the spinning beacon (Sea Lantern) too based on the power... I just found some weird graphical issues that meant the block stopped spinning when you were stood in certain places looking at the Controller.  Yeah, I cut the top left button off but I think I should go for a smaller grid or line too.  I like the suggestion of "dumbing down"(?) the texture and making it less high-res and will take a look this evening.  Same as the Controller having a second circle to make a seal.

I appreciate the suggestions, however, as I am not an artist at any level - the artwork was whipped up in about 5 minutes in Paint.NET as I know I can't really do much better! So any aesthetic suggestions are greatly appreciated.

**Comment by VallenFrostweaver** [comment]
Heh. Gotcha. Forge power... I can't even think of a mod that uses that myself since I've always used the others. >.> Maybe it's time I diversify more.  
As for textures, you at least have them and they look better than draconic armor so I call that a win. ;) I'm sure that if you put out a request (with some specifics) you may be able to get a texture artist to help you out. While I do have some level of artistic talent I've no idea how I would be able to put anything in a way that you could use it as I am very bad when it comes to programming.

**Comment by VallenFrostweaver** [comment]
Let me know again when you think you might have the power sorted and I'll see about taking a crack at that coverage. As it is at the moment, I think I'd have a lot of people come off angry at the mod and even if changed later they would have a bad first impression. I'd rather push this mod out there with as much positive as I can to make a lasting positive impression. :)

**Comment by ArclightTW** [comment]
> Heh. Gotcha. Forge power...

I think they (the Forge guys) are trying to encourage people to use the inbuilt system to allow more cross-compatibility so we don't run into issues exactly like this.  I have tried to implement some of the APIs before but not in a properly released mod, so here goes getting it to work properly.  At least, at this time, anyway, there is only 1 block that actually does any actual power generation in the internal logic; that makes life a touch easier, at least.

> As for textures, ...

It is something that I want to do as the mod progresses onwards, perhaps getting an early post out to bring some people onboard is a good idea before things get bigger.  Although, with any luck, there shouldn't be too much more that needs adding since it's meant to be a fairly simple, early game power source that can be expanded to support late game too.

> Let me know again...

I couldn't agree more and have updated the CurseForge page to notify users that only Forge Energy is supported at this time.  I appreciate you taking the time to hang around the mod and help get it to a positive state rather than being one of the people that would come off angry at it and not use it again.

**Comment by VallenFrostweaver** [comment]
Happy to help. I like mods like this. Looking forward to more. :)

**Comment by ArclightTW** [comment]
RF is now supported, recipes are fixed, I believe everything is fixed at this time.  Check out v0.3.1 :)

Let me know if everything is resolved and I will close this issue down.

**Comment by ArclightTW** [comment]
Closing this issue as no response has been received. I believe RF generation works with Thermal machines but not with Immersive Engineering or Actually Additions; this is a known bug that is being worked on.
